version: '3'

volumes:
  db-data:
    external: false

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/beenshortened-api_development
      RAILS_ENV: 'development'
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: